### ISSUE TITLE
build isuue

### ISSUE THREAD

**Issue by jlxy11** [lavenklau/homo3d#6]
[  2%] Building CUDA object CMakeFiles/cubin.dir/Framework.cu.o
[  3%] Building CXX object _deps/openvdb-build/openvdb/openvdb/CMakeFiles/openvdb_static.dir/Grid.cc.o
In file included from /home/jiangyi/11/homo3d-master/homo3d-master/AutoDiff/TensorExpression.h:2:0,
                 from /home/jiangyi/11/homo3d-master/homo3d-master/AutoDiff/TensorExpression.cu:1:
/home/jiangyi/11/homo3d-master/homo3d-master/AutoDiff/AutoDiff.h:15:10: fatal error: cuda/std/tuple: 没有那个文件或目录
 #include <cuda/std/tuple>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/cubin.dir/build.make:63：CMakeFiles/cubin.dir/AutoDiff/TensorExpression.cu.o] 错误 1
make[2]: *** 正在等待未完成的任务....
[  5%] Building CXX object _deps/openvdb-build/openvdb/openvdb/CMakeFiles/openvdb_shared.dir/Grid.cc.o
[  5%] Building CXX object _deps/openvdb-build/openvdb/openvdb/CMakeFiles/openvdb_static.dir/io/Archive.cc.o
In file included from /home/jiangyi/11/homo3d-master/homo3d-master/homogenization/homoExpression.h:3:0,
                 from /home/jiangyi/11/homo3d-master/homo3d-master/homogenization/Framework.cuh:2,
                 from /home/jiangyi/11/homo3d-master/homo3d-master/Framework.cu:1:
/home/jiangyi/11/homo3d-master/homo3d-master/AutoDiff/AutoDiff.h:15:10: fatal error: cuda/std/tuple: 没有那个文件或目录
 #include <cuda/std/tuple>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/cubin.dir/build.make:76：CMakeFiles/cubin.dir/Framework.cu.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:168：CMakeFiles/cubin.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[  6%] Building CXX object _deps/openvdb-build/openvdb/openvdb/CMakeFiles/openvdb_static.dir/io/Compression.cc.o

**Comment by jlxy11** [comment]
build with ubuntu 20.04 and cuda11.1

**Comment by lavenklau** [comment]
Sorry for the late comment.  Have you solved your issue? @jlxy11

**Comment by jlxy11** [comment]
> Sorry for the late comment. Have you solved your issue? @jlxy11

still not, could you share your building environment？

**Comment by jlxy11** [comment]
> Sorry for the late comment. Have you solved your issue? @jlxy11

still not, could you share your building environment？@lavenklau

**Comment by jlxy11** [comment]
https://nvidia.github.io/libcudacxx/standard_api/utility_library/tuple.html
<cuda/std/tuple>
Restrictions
Before version 1.4.0, tuple is not available when using NVCC with MSVC as a host compiler, due to compiler bugs.

Internal compiler errors may be encountered when using tuple with older updates of MSVC 2017 and MSVC 2019. For MSVC 2017, please use version 15.8 or later (_MSC_VER >= 1915). For MSVC 2019, please use version 16.6 or later (_MSC_VER >= 1926).

**Comment by lavenklau** [comment]
I build the project on wsl2 (Ubuntu 20.04) with g++ 9.4 and cuda 11.4, everything seems fine. Are you building it on windows? @jlxy11

**Comment by jlxy11** [comment]
> I build the project on wsl2 (Ubuntu 20.04) with g++ 9.4 and cuda 11.4, everything seems fine. Are you building it on windows? @jlxy11

Thank you for your reply. I built it on Ubuntu20.04. I will reconfigure it completely according to your environment later.

**Comment by jlxy11** [comment]
> I build the project on wsl2 (Ubuntu 20.04) with g++ 9.4 and cuda 11.4, everything seems fine. Are you building it on windows? @jlxy11

**hello! I reconfigure it completely according to your environment !**
(homo3d) jy@jy:~/homo3d-master/build$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jun__2_19:15:15_PDT_2021
Cuda compilation tools, release 11.4, V11.4.48
Build cuda_11.4.r11.4/compiler.30033411_0
(homo3d) jy@jy:~/homo3d-master/build$ gcc --version
gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR /home/jy/anaconda3/envs/homo3d/include/glm/detail/type_mat3x3.inl(471): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
/usr/local/cuda-11.4/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(204): here
A PARTICULAR PURPOSE.

(homo3d) jy@jy:~/homo3d-master/build$ g++ --v/home/jy/anaconda3/envs/homo3d/include/glm/detail/type_mat3x3.inl(471): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
/usr/local/cuda-11.4/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(204): here
ersion
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**but I came up with:**

/home/jy/anaconda3/envs/homo3d/include/glm/detail/type_mat3x3.inl(471): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
/usr/local/cuda-11.4/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(204): here

**Comment by jlxy11** [comment]
Specifying GPU architecture (-arch=sm_xx) as compiler flag can solve this error.but I am new to cuda, could you please tell me how to Specifying GPU architecture? my nvidia card is rtx 1650 laptop
https://github.com/NVIDIA/cutlass/issues/4

**Comment by jlxy11** [comment]
> Specifying GPU architecture (-arch=sm_xx) as compiler flag can solve this error.but I am new to cuda, could you please tell me how to Specifying GPU architecture? my nvidia card is rtx 1650 laptop [NVIDIA/cutlass#4](https://github.com/NVIDIA/cutlass/issues/4)

**I have compiler this program but I came up with** 
./homo3d -reso 128 -obj bulk -init randc -sym reflect6 -vol 0.3 -mu 0.3
......
searching level set isovalue t = 7.90e-01 , v = 29.62% , it = 15  
searching level set isovalue t = 7.34e-01 , v = 29.87% , it = 16   

CUDA error occured at line 2737 in file /home/jy/homo3d-master/homogenization/grid.cu, error type cudaErrorMisalignedAddress 
CUDA error occured at line 2427 in file /home/jy/homo3d-master/homogenization/grid.cu, error type cudaErrorMisalignedAddress 
CUDA error occured at line 2435 in file /home/jy/homo3d-master/homogenization/grid.cu, error type cudaErrorMisalignedAddress 
......
CUDA error occured at line 736 in file /home/jy/homo3d-master/culib/gpuVector.cuh, error type cudaErrorMisalignedAddress 
Free buffer failed with err cudaErrorCudartUnloading, memType Device
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to Free memory
已放弃 (核心已转储)

**Comment by lavenklau** [comment]
> Specifying GPU architecture (-arch=sm_xx) as compiler flag can solve this error.but I am new to cuda, could you please tell me how to Specifying GPU architecture? my nvidia card is rtx 1650 laptop [NVIDIA/cutlass#4](https://github.com/NVIDIA/cutlass/issues/4)

You may refer to [](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#feature-availability) and [](https://developer.nvidia.com/cuda-gpus) @jlxy11

**Comment by lavenklau** [comment]
You may refer to https://developer.nvidia.com/cuda-gpus and https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#feature-availability @jlxy11

**Comment by lavenklau** [comment]
> > Specifying GPU architecture (-arch=sm_xx) as compiler flag can solve this error.but I am new to cuda, could you please tell me how to Specifying GPU architecture? my nvidia card is rtx 1650 laptop [NVIDIA/cutlass#4](https://github.com/NVIDIA/cutlass/issues/4)
> 
> **I have compiler this program but I came up with** ./homo3d -reso 128 -obj bulk -init randc -sym reflect6 -vol 0.3 -mu 0.3 ...... searching level set isovalue t = 7.90e-01 , v = 29.62% , it = 15 searching level set isovalue t = 7.34e-01 , v = 29.87% , it = 16
> 
> CUDA error occured at line 2737 in file /home/jy/homo3d-master/homogenization/grid.cu, error type cudaErrorMisalignedAddress CUDA error occured at line 2427 in file /home/jy/homo3d-master/homogenization/grid.cu, error type cudaErrorMisalignedAddress CUDA error occured at line 2435 in file /home/jy/homo3d-master/homogenization/grid.cu, error type cudaErrorMisalignedAddress ...... CUDA error occured at line 736 in file /home/jy/homo3d-master/culib/gpuVector.cuh, error type cudaErrorMisalignedAddress Free buffer failed with err cudaErrorCudartUnloading, memType Device terminate called after throwing an instance of 'std::runtime_error' what(): failed to Free memory 已放弃 (核心已转储)

Have you tried other device?  My  gtx1080ti works normally.

**Comment by jlxy11** [comment]
*

> > > Specifying GPU architecture (-arch=sm_xx) as compiler flag can solve this error.but I am new to cuda, could you please tell me how to Specifying GPU architecture? my nvidia card is rtx 1650 laptop [NVIDIA/cutlass#4](https://github.com/NVIDIA/cutlass/issues/4)
> > 
> > 
> > **I have compiler this program but I came up with** ./homo3d -reso 128 -obj bulk -init randc -sym reflect6 -vol 0.3 -mu 0.3 ...... searching level set isovalue t = 7.90e-01 , v = 29.62% , it = 15 searching level set isovalue t = 7.34e-01 , v = 29.87% , it = 16
> > CUDA error occured at line 2737 in file /home/jy/homo3d-master/homogenization/grid.cu, error type cudaErrorMisalignedAddress CUDA error occured at line 2427 in file /home/jy/homo3d-master/homogenization/grid.cu, error type cudaErrorMisalignedAddress CUDA error occured at line 2435 in file /home/jy/homo3d-master/homogenization/grid.cu, error type cudaErrorMisalignedAddress ...... CUDA error occured at line 736 in file /home/jy/homo3d-master/culib/gpuVector.cuh, error type cudaErrorMisalignedAddress Free buffer failed with err cudaErrorCudartUnloading, memType Device terminate called after throwing an instance of 'std::runtime_error' what(): failed to Free memory 已放弃 (核心已转储)
> 
> Have you tried other device? My gtx1080ti works normally.

**hello!I am wondering did the program run successfully like this?
I reconfigure it on wsl2 (Ubuntu 20.04) with g++ 9.4 and cuda 12.0,and my nvidia card is rtx 4080 laptop.**

[CUDA] bank Width = 4
Sensitivity analysis using managed memory...

 * Iter 95   obj = -2.7119e+00
max sens = 0.000024
[OC] : g = 1.1328e-05   vol = 30.00% (Goal 30.00%)       
Coarse system degenerate rank = 3
[CUDA] bank Width = 8
rel_res = 0.51%    It.1       
rel_res = 0.54%    It.1       
rel_res = 0.59%    It.1       
rel_res = 0.17%    It.2       
rel_res = 0.19%    It.2       
rel_res = 0.94%    It.1       
n_cell = 2097152
[CUDA] bank Width = 4
Sensitivity analysis using managed memory...

 * Iter 96   obj = -2.7119e+00
= converged
(homo3d) jy@jy:~/test/homo3d-master/build$

**Comment by lavenklau** [comment]
Yes, the program exit normally,   the optimized density field is stored in the output file `rho` or `density`, they are both OpenVDB file (wihout the `.vdb` extension name).

**Comment by jlxy11** [comment]
> Yes, the program exit normally, the optimized density field is stored in the output file `rho` or `density`, they are both OpenVDB file (wihout the `.vdb` extension name).

Thank you for your patience and have a nice time！
